### ISSUE TITLE
Peer-to-peer program reviewing - Morning-session 

### ISSUE THREAD

**Issue by wajahatalli** [Tekhlay/microverse-portfolio-website#7]
# Highlights

- You did a good job implementing the Figma design :+1: 
- Clean code base :100: 
- Great gitflow work :+1: 
- No linter errors  👌
- Good job using transitions & animations  🤝

# Suggestions

- [ ] Please Add some padding in the input of the Comment area of the Contact form.
- [ ] Please add some duration in animations to make it look more natural, so it doesn't appear in an instant.
- [ ] Please consider changing the spelling in the comment area of the Contact form, from "Typing" to "Type" to make it grammatically correct.

**Comment by Tekhlay** [comment]
Thanks for your constractive suggestions. All things are corrected an modified now.
